export const SimalsiRoles = {
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_CLIENTE: 'ROLE_CLIENTE',
  ROLE_RECEPCIONISTA: 'ROLE_RECEPCIONISTA',
  ROLE_HISTOTECNOLOGO: 'ROLE_HISTOTECNOLOGO',
  ROLE_PATOLOGO: 'ROLE_PATOLOGO',
} as const
